dist: trusty

jobs:
  include:
  - stage: build
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - bash scripts/publish-grpc.sh
    - bash scripts/publish-http.sh
    if: branch = master